# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edx < Formula
  desc "Edge Delta command-line interface"
  homepage "https://github.com/edgedelta/edx"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edgedelta/edx/releases/download/v0.2.0/edx_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "140bdb4b470b60314fcfbdcb0ca67d16d2b19e1021720edadde70c97bec96679"

      define_method(:install) do
        bin.install "edx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edgedelta/edx/releases/download/v0.2.0/edx_0.2.0_Darwin_arm64.tar.gz"
      sha256 "429a1b387b43571244bd118e726216f50e6653956577e5b2d6e71361e757e36f"

      define_method(:install) do
        bin.install "edx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edgedelta/edx/releases/download/v0.2.0/edx_0.2.0_Linux_x86_64.tar.gz"
      sha256 "cd7f282f7c650d87bb42ac15606b77a5435c66eb53381264e79e795023489d09"
      define_method(:install) do
        bin.install "edx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edgedelta/edx/releases/download/v0.2.0/edx_0.2.0_Linux_arm64.tar.gz"
      sha256 "9d9d5c32a146e2249b6af411303c5d365a5dba873b2d29f4bf6b50a5afe896d1"
      define_method(:install) do
        bin.install "edx"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/edx version")
  end
end
